### ISSUE TITLE
Kijk nog even naar de indeling van bestanden op GitHub

### ISSUE THREAD

**Issue by joostf** [DominiqueM96/Verhalen-website#1]
Zet de bestanden en subfolders van je website direct in de root van de repository. en noem je html bestand index.html, dat maakt hetlater makkelijker om je website te bekijken

**Comment by DominiqueM96** [comment]
Ik heb mijn indeling aangepast alleen kan ik nergens de oude bestanden verwijderen

**Comment by DominiqueM96** [comment]
heb de foute bestanden verwijderd en nu de goede indeling gedaan
