### ISSUE TITLE
Formulier semantiek verbeteren

### ISSUE THREAD

**Issue by joostf** [DominiqueM96/Verhalen-website#3]
Zet de heading in het formulier en maak er een legend in een fieldset van:
https://github.com/DominiqueM96/Verhalen-website/blob/master/verhalen%20website%20html/index2.html#L27

Geef elke checkbox een label:
https://github.com/DominiqueM96/Verhalen-website/blob/master/verhalen%20website%20html/index2.html#L31

**Comment by DominiqueM96** [comment]
fieldset en labels toegevoegd
